global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kafka-broker'
    scrape_interval: 5s
    scrape_timeout: 4s
    static_configs:
      - targets:
        - 'broker-1:7071'
        - 'broker-2:7071'
        - 'broker-3:7071'

  - job_name: 'spark-master'
    scrape_interval: 5s
    static_configs:
      - targets: ['spark-master:7072']

  - job_name: 'spark-worker'
    scrape_interval: 5s
    static_configs:
      - targets: ['spark-worker-1:7073']

  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'spark-streaming'
    scrape_interval: 5s
    static_configs:
      - targets: 
        - 'spark-streaming-submissions:7074'
        - 'spark-streaming-comments:7075'